services:
  - type: web
    name: job-alert-bot-python
    env: python
    buildCommand: |
      pip install -r requirements.txt
      python -m playwright install chromium
    startCommand: python main.py
    envVars:
      - key: TELEGRAM_BOT_TOKEN
        sync: false
      - key: CHAT_ID
        sync: false
