services:
  - type: web
    name: amazon-job-bot
    env: python
    plan: free
    buildCommand: |
      pip install -r requirements.txt
      python -m playwright install chromium
    startCommand: python main2.py