services:
  - type: worker
    name: job-alert-bot
    env: python
    buildCommand: |
      pip install -r requirements.txt
      python -m playwright install chromium
    startCommand: gunicorn main_offline_persistent:app --bind 0.0.0.0:$PORT --workers 1
    envVars:
      - key: TELEGRAM_BOT_TOKEN
        value: 8214392800:AAGrRksRKpAD8Oa8H4aByo5XKSwc_9SM9Bo
      - key: TELEGRAM_CHAT_ID
        value: 7943617436
