services:
  - type: web
    name: amazon-jobs-live
    env: python
    buildCommand: |
      pip install -r requirements.txt
      playwright install chromium
    startCommand: python main_online.py
    plan: free
    envVars:
      - key: TELEGRAM_TOKEN
        value: 8214392800:AAGrRksRKpAD8Oa8H4aByo5XKSwc_9SM9Bo
      - key: CHAT_ID
        value: 7943617436
